# Generated by Django 6.0.4 on 2026-04-14 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('caption', models.TextField(blank=True, max_length=500, verbose_name='caption')),
                ('video', models.FileField(help_text='Upload MP4 video (max 60 seconds)', upload_to='reels/videos/%Y/%m/', verbose_name='video')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='reels/thumbnails/%Y/%m/', verbose_name='thumbnail')),
                ('audio_title', models.CharField(blank=True, help_text='Background music/audio name', max_length=200, verbose_name='audio title')),
                ('audio_artist', models.CharField(blank=True, max_length=100, verbose_name='audio artist')),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only'), ('private', 'Only Me')], default='public', max_length=10, verbose_name='privacy')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='allow comments')),
                ('allow_duet', models.BooleanField(default=True, verbose_name='allow duet')),
                ('is_draft', models.BooleanField(default=False, verbose_name='draft')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Video duration in seconds')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reel',
                'verbose_name_plural': 'reels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reels.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reel comment',
                'verbose_name_plural': 'reel comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reels.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reel like',
                'verbose_name_plural': 'reel likes',
            },
        ),
        migrations.CreateModel(
            name='ReelSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='reels.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saved reel',
                'verbose_name_plural': 'saved reels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='reels.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reel share',
                'verbose_name_plural': 'reel shares',
            },
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['-created_at'], name='reels_reel_created_cb43dd_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['author', '-created_at'], name='reels_reel_author__615b20_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['view_count'], name='reels_reel_view_co_4f0225_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reellike',
            unique_together={('user', 'reel')},
        ),
        migrations.AlterUniqueTogether(
            name='reelsave',
            unique_together={('user', 'reel')},
        ),
        migrations.AlterUniqueTogether(
            name='reelshare',
            unique_together={('user', 'reel')},
        ),
    ]
