# Generated by Django 6.0.4 on 2026-06-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.PositiveIntegerField(default=0, help_text='Earned through platform activity. Used to change username.', verbose_name='coins'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='10-digit mobile number (e.g. 9876543210)', max_length=15, null=True, unique=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='username_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='username changed at'),
        ),
        migrations.AddField(
            model_name='user',
            name='username_locked',
            field=models.BooleanField(default=True, help_text='If True, username cannot be changed without spending coins.', verbose_name='username locked'),
        ),
    ]
