# Generated by Django 6.0.4 on 2026-04-15 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_likes', models.BooleanField(default=True)),
                ('email_comments', models.BooleanField(default=True)),
                ('email_follows', models.BooleanField(default=True)),
                ('email_job_updates', models.BooleanField(default=True)),
                ('email_webinar_reminders', models.BooleanField(default=True)),
                ('email_group_activity', models.BooleanField(default=True)),
                ('push_likes', models.BooleanField(default=True)),
                ('push_comments', models.BooleanField(default=True)),
                ('push_follows', models.BooleanField(default=True)),
                ('push_job_updates', models.BooleanField(default=True)),
                ('push_webinar_reminders', models.BooleanField(default=True)),
                ('push_group_activity', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=False)),
                ('weekly_digest', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('friend_request', 'Friend Request'), ('friend_accept', 'Friend Request Accepted'), ('job_application', 'Job Application'), ('job_status', 'Job Status Update'), ('webinar_reminder', 'Webinar Reminder'), ('webinar_start', 'Webinar Starting'), ('group_invite', 'Group Invitation'), ('group_join', 'Group Join Request'), ('mention', 'Mention'), ('share', 'Share'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_emailed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user notification',
                'verbose_name_plural': 'user notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='user_notifi_recipie_0b8960_idx'), models.Index(fields=['recipient', 'is_read'], name='user_notifi_recipie_cc859a_idx')],
            },
        ),
    ]
