# Generated by Django 6.0.4 on 2026-04-14 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='category name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon name', max_length=50)),
            ],
            options={
                'verbose_name': 'research category',
                'verbose_name_plural': 'research categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('abstract', models.TextField(max_length=2000, verbose_name='abstract')),
                ('keywords', models.CharField(help_text='Comma separated keywords', max_length=500, verbose_name='keywords')),
                ('additional_authors', models.TextField(blank=True, help_text='Authors not on platform (Name; Institution)', verbose_name='additional authors')),
                ('file', models.FileField(help_text='Upload PDF file', upload_to='research/papers/%Y/%m/', verbose_name='paper file')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='research/covers/%Y/%m/', verbose_name='cover image')),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier (if published)', max_length=100, unique=True, verbose_name='DOI')),
                ('journal_name', models.CharField(blank=True, max_length=200, verbose_name='journal/conference name')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='publication date')),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('registered', 'Registered Users Only'), ('private', 'Private')], default='public', max_length=15, verbose_name='access level')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('under_review', 'Under Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=15, verbose_name='status')),
                ('allow_comments', models.BooleanField(default=True)),
                ('allow_download', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('version_notes', models.TextField(blank=True, help_text='What changed in this version?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('citation_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='research.researchcategory')),
                ('co_authors', models.ManyToManyField(blank=True, related_name='co_authored_papers', to=settings.AUTH_USER_MODEL, verbose_name='co-authors')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_versions', to='research.researchpaper')),
                ('primary_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_papers', to=settings.AUTH_USER_MODEL, verbose_name='primary author')),
            ],
            options={
                'verbose_name': 'research paper',
                'verbose_name_plural': 'research papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_papers', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='research.researchpaper')),
            ],
            options={
                'verbose_name': 'saved paper',
                'verbose_name_plural': 'saved papers',
            },
        ),
        migrations.CreateModel(
            name='PaperLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='research.researchpaper')),
            ],
            options={
                'verbose_name': 'paper like',
                'verbose_name_plural': 'paper likes',
            },
        ),
        migrations.CreateModel(
            name='PaperComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('is_review', models.BooleanField(default=False, help_text='Is this a formal peer review?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='research.researchpaper')),
            ],
            options={
                'verbose_name': 'paper comment',
                'verbose_name_plural': 'paper comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearcherFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_researchers', to=settings.AUTH_USER_MODEL)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'researcher follow',
                'verbose_name_plural': 'researcher follows',
                'unique_together': {('follower', 'researcher')},
            },
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['-created_at'], name='research_re_created_d30ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['title'], name='research_re_title_91a9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['primary_author', '-created_at'], name='research_re_primary_d3da1d_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['category', '-created_at'], name='research_re_categor_238644_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='papersave',
            unique_together={('user', 'paper')},
        ),
        migrations.AlterUniqueTogether(
            name='paperlike',
            unique_together={('user', 'paper')},
        ),
    ]
