# Generated by Django 6.0.4 on 2026-04-14 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='category name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'webinar category',
                'verbose_name_plural': 'webinar categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(max_length=5000, verbose_name='description')),
                ('thumbnail', models.ImageField(blank=True, upload_to='webinars/thumbnails/%Y/%m/', verbose_name='thumbnail')),
                ('cover_image', models.ImageField(blank=True, upload_to='webinars/covers/%Y/%m/', verbose_name='cover image')),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=500, verbose_name='tags')),
                ('scheduled_at', models.DateTimeField(verbose_name='scheduled date and time')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='duration (minutes)')),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('access_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('private', 'Private/Invite Only')], default='free', max_length=10, verbose_name='access type')),
                ('max_attendees', models.PositiveIntegerField(default=100, verbose_name='max attendees')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='registration deadline')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='price')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('room_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('jitsi_server', models.URLField(default='https://meet.jit.si')),
                ('enable_chat', models.BooleanField(default=True, verbose_name='enable live chat')),
                ('enable_qa', models.BooleanField(default=True, verbose_name='enable Q&A')),
                ('enable_recording', models.BooleanField(default=True, verbose_name='enable recording')),
                ('auto_record', models.BooleanField(default=False, verbose_name='auto record')),
                ('require_registration', models.BooleanField(default=True, verbose_name='require registration')),
                ('send_reminders', models.BooleanField(default=True, verbose_name='send email reminders')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live Now'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='draft', max_length=15, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('recording_url', models.URLField(blank=True, verbose_name='recording URL')),
                ('recording_duration', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('registration_count', models.PositiveIntegerField(default=0)),
                ('attendance_count', models.PositiveIntegerField(default=0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_webinars', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinars', to='webinars.webinarcategory')),
            ],
            options={
                'verbose_name': 'webinar',
                'verbose_name_plural': 'webinars',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('is_answered', models.BooleanField(default=False)),
                ('answer', models.TextField(blank=True)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_questions', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='webinars.webinar')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['-upvotes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_ratings', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='webinars.webinar')),
            ],
            options={
                'verbose_name': 'rating',
                'verbose_name_plural': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='registered', max_length=15)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_url', models.URLField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_registrations', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='webinars.webinar')),
            ],
            options={
                'verbose_name': 'webinar registration',
                'verbose_name_plural': 'webinar registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='webinars/certificates/%Y/%m/')),
                ('qr_code', models.ImageField(blank=True, upload_to='webinars/qrcodes/%Y/%m/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('verification_url', models.URLField(blank=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='webinars.webinarregistration')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='WebinarSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_sessions', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='webinars.webinar')),
            ],
            options={
                'verbose_name': 'webinar session',
                'verbose_name_plural': 'webinar sessions',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['scheduled_at'], name='webinars_we_schedul_635b05_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['status', 'scheduled_at'], name='webinars_we_status_46cd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['host', 'scheduled_at'], name='webinars_we_host_id_da5b59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webinarrating',
            unique_together={('webinar', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='webinarregistration',
            unique_together={('webinar', 'user')},
        ),
    ]
